name: Upload to s3 serverless Bucket
on:
  pull_request:
    branches:
      - main
jobs:
  move:
    runs-on: ubuntu-latest
    name: Upload Files
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Setup Java Environment
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
   
      - name: Build with Maven
        run: |
             mvn -B package --file pom.xml
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.MY_ACCESS_KEY_LAMBDA}}
          aws-secret-access-key: ${{secrets.MY_SECRET_KEY_LAMBDA}}
          aws-region: us-east-1

      - name: sync s3
        run: |
          aws s3 sync ./serverless/target/ s3://${{secrets.MY_LAMBDA_BUCKET}}



      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          cd /serverless/target
          aws lambda update-function-code --function-name csye6225-spring2022 --zip-file fileb://serverless-1.0.0.jar
